parameters:
#    devilcius_admin_menu.example.class: devilcius\AdminMenuBundle\Example

services:
#    devilcius_admin_menu.example:
#        class: %devilcius_admin_menu.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
